// Happy, Neutral, Suprise, Sad, Angry, Fear, Disgust

export const emotionMapping = { 
    happy: {
      mouthOpen: 0.31,
      mouthSmile: 0.83,
      browInnerUp: 0.45,
      browOuterUpLeft: 0.47,
      browOuterUpRight: 0.47,
      eyeSquintRight: 0.18,
      eyeSquintLeft: 0.18,
    },
    neutral: {
      mouthOpen: 0,
      mouthSmile: 0,
      browInnerUp: 0,
      browOuterUpLeft: 0,
      browOuterUpRight: 0,
      eyeSquintRight: 0,
      eyeSquintLeft: 0,
    },
    sad: {
      browInnerUp: 0.67,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      mouthFrownLeft: 1,
      mouthFrownRight: 1,
      mouthShrugLower: 0.34,
      eyesLookDown: 0.41,
    },
    angry: {
      browDownLeft: 0.82,
      browDownRight: 0.82,
      browOuterUpLeft: 0.66,
      browOuterUpRight: 0.66,
      jawForward: 1,
      mouthFrownLeft: 0.51,
      mouthFrownRight: 0.51,
      mouthShrugLower: 0.52,
      mouthShrugUpper:0.27,
      noseSneerLeft: 1,
      noseSneerRight: 1,
    },
    surprise: {
      mouthOpen: 1,
      viseme_SS: 0.46,
      viseme_O: 0.49,
      browInnerUp: 1,
      browOuterUpLeft: 0.7,
      browOuterUpRight: 0.7,
      eyeWideLeft: 0.43,
      eyeWideRight: 0.43,
      mouthFrownLeft: 0.52,
      mouthFrownRight: 0.52,
      mouthShrugLower: 1,
      mouthShrugUpper: 0.25,
    },
    fear: {
      viseme_O: 0.42,
      browInnerUp: 0.78,
      eyeSquintLeft: 0.5,
      eyeSquintRight: 0.5,
      eyeWideLeft: 0.43,
      eyeWideRight: 0.43,
      mouthFrownLeft: 0.5,
      mouthFrownRight: 0.5,
      mouthShrugLower: 1,
      mouthShrugUpper: 0.25,
      eyesLookDown: 0.16,
    }, 
    disgust: {
      viseme_O: 0.32,
      browDownRight: 0.45,
      browInnerUp: 0.78,
      browOuterUpLeft: 0.44,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      eyeWideRight: 0.43,
      eyeWideLeft: 0.43,
      mouthFrownLeft: 0.45,
      mouthFrownRight: 0.45,
      mouthShrugLower: 1,
      noseSneerRight: 1,
      mouthUpperUpRight: 0.88,
    },
  };
  